Fix: a bug in hashtables schema
Artefact of Apollo compatibility that stores

`repo_id//path@sha1` in `sha1` column, instead of 3 separate cols.

Otherwise, it would lead to things like:

```
com.datastax.driver.core.exceptions.InvalidTypeException: github.com/
kfkme/kfkweb//web/企业网站/外卖PC端饿了么/js/vendor_rebuild.e3fae7ec.js@b3de9d86
cdf305c8ff499c474fcd534b49fa3ebb is not a valid ASCII String
```

Signed-off-by: Alexander Bezzubov <bzz@apache.org>